version: '3.1'
services:
  farming-mongo:
    build:
      context: .
      dockerfile: ./.docker/mongo.Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - "${MONGO_HOST_PORT}:27017"  
    volumes:
      - farming_mongodb:/data/db

  farming-react:
    build:
      context: .
      dockerfile: ./.docker/app.Dockerfile
    env_file: 
      - .env
    command: sh -c "${INITIAL_COMMAND}"
    ports:
      - "${REACT_HOST_PORT}:${REACT_CONTAINER_PORT}"  
     
    volumes:
      - .:/usr/app
      - node_modules_farming:/usr/app/node_modules 
      - node_modules_farming_types:/usr/app/node_modules/@types
  
  farming-mqtt:
    build:
      context: .
      dockerfile: ./.docker/rabbit.Dockerfile
      args: 
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always
    env_file: 
      # https://forums.docker.com/t/environment-variables-in-args/27522
      - .env
    volumes:
      - farming_rabbitmq_data:/var/lib/rabbitmq/
      - farming_rabbitmq_logs:/var/log/rabbitmq/
      # - farming_rabbitmq_etc:/etc/rabbitmq/
    ports:
      - 1883:1883  
      - 15675:15675
      - 5672:5672
      - 5671:5671
      - 15672:15672
      - 15673:15673
      - 15671:15671
  
      
      
volumes:
  farming_mongodb:
  node_modules_farming:
  node_modules_farming_types:
    driver: local
    driver_opts:
      type: none
      device: $PWD/@types
      o: bind
  farming_rabbitmq_etc:
  farming_rabbitmq_data:
  farming_rabbitmq_logs: